pull_request_rules:
  - name: automatic merge master to develop branch
    conditions:
      - head=master
      - base=develop
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge

  - name: automatic merge for develop
    conditions:
      - "-head=master"
      - "#approved-reviews-by>=1"
      - base=develop
    actions:
      merge:
        method: merge

  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
    actions:
      merge:
        method: merge
