name: auto_approve

on:
  pull_request:
  check_run:
    types: [completed]

jobs:
  build:
    name: auto approve
    runs-on: ubuntu-latest
    steps:
      - name: auto approve rebase
        uses: hmarr/auto-approve-action@v2.0.0
        if: github.head_ref == 'master' && github.base_ref == 'develop'
        with:
          github-token: '${{ secrets.BOT_GITHUB_TOKEN }}'
      - name: auto approve imgbot
        uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'imgbot[bot]'
        with:
          github-token: '${{ secrets.BOT_GITHUB_TOKEN }}'
      - name: auto approve schmas
        uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'schmas'
        with:
          github-token: '${{ secrets.BOT_GITHUB_TOKEN }}'
