name: build

on:
  repository_dispatch
  # push:
  #   branches:
  #   - master
  # pull_request:
  #   branches:
  #   - master
  #   - develop

jobs:
  build:
    timeout-minutes: 10
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 8.x

      - name: Get npm env
        id: npm-env
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
          echo "::set-output name=vscode_version::$(npm run get-vscode-version --silent)"

      # - name: Cache npm
      #   uses: actions/cache@v1
      #   if: runner.os != 'Windows'
      #   with:
      #     path: ${{ steps.npm-env.outputs.dir }}
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-

      # - name: Cache vscode-test
      #   id: cache-vscode-test
      #   uses: actions/cache@v1
      #   with:
      #     path: .vscode-test
      #     key: ${{ runner.os }}-vscode-test-${{ steps.npm-env.outputs.vscode_version }}

      - run: npm install

      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm test
